networks:
  commitinder:
    driver: bridge
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD", "ls" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - commitinder:/var/lib/postgresql
    networks:
      - commitinder

  api:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - commitinder
volumes: 
  commitinder:
  
