networks:
  commitinder:
    driver: bridge
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ~/Commitinder:/var/lib/postgresql
    networks:
      - commitinder

  api:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - commitinder
