package seeds

import (
	"commitinder/database"
	"commitinder/models"
)

func SeedDuels(userId int) {

	var user models.User
	_ = database.Db.GetUserById(userId, &user)

	var duels []models.Duel

	_ = database.Db.GetAllDuels(&duels)

	if len(duels) > 0 {
		for _, duel := range duels {
			duel.Users = append(duel.Users, user)
			database.Db.UpdateDuel(&duel)
		}
		return
	}

	users := []models.User{user}

	seeds := []models.Duel{
		{Users: users, CommitMessageAId: 3, CommitMessageBId: 4},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 7, CommitMessageBId: 8},
{Users: users, CommitMessageAId: 10, CommitMessageBId: 11},
{Users: users, CommitMessageAId: 14, CommitMessageBId: 15},
{Users: users, CommitMessageAId: 17, CommitMessageBId: 20},
{Users: users, CommitMessageAId: 21, CommitMessageBId: 24},
{Users: users, CommitMessageAId: 28, CommitMessageBId: 27},
{Users: users, CommitMessageAId: 31, CommitMessageBId: 29},
{Users: users, CommitMessageAId: 36, CommitMessageBId: 33},
{Users: users, CommitMessageAId: 40, CommitMessageBId: 37},
{Users: users, CommitMessageAId: 42, CommitMessageBId: 41},
{Users: users, CommitMessageAId: 46, CommitMessageBId: 48},
{Users: users, CommitMessageAId: 49, CommitMessageBId: 52},
{Users: users, CommitMessageAId: 53, CommitMessageBId: 54},
{Users: users, CommitMessageAId: 60, CommitMessageBId: 59},
{Users: users, CommitMessageAId: 62, CommitMessageBId: 63},
{Users: users, CommitMessageAId: 65, CommitMessageBId: 67},
{Users: users, CommitMessageAId: 72, CommitMessageBId: 71},
{Users: users, CommitMessageAId: 74, CommitMessageBId: 75},
{Users: users, CommitMessageAId: 80, CommitMessageBId: 78},
{Users: users, CommitMessageAId: 83, CommitMessageBId: 81},
{Users: users, CommitMessageAId: 87, CommitMessageBId: 88},
{Users: users, CommitMessageAId: 89, CommitMessageBId: 91},
{Users: users, CommitMessageAId: 94, CommitMessageBId: 96},
{Users: users, CommitMessageAId: 100, CommitMessageBId: 98},
{Users: users, CommitMessageAId: 101, CommitMessageBId: 102},
{Users: users, CommitMessageAId: 108, CommitMessageBId: 107},
{Users: users, CommitMessageAId: 112, CommitMessageBId: 111},
{Users: users, CommitMessageAId: 114, CommitMessageBId: 115},
{Users: users, CommitMessageAId: 120, CommitMessageBId: 117},
{Users: users, CommitMessageAId: 124, CommitMessageBId: 123},
{Users: users, CommitMessageAId: 127, CommitMessageBId: 125},
{Users: users, CommitMessageAId: 131, CommitMessageBId: 129},
{Users: users, CommitMessageAId: 133, CommitMessageBId: 134},
{Users: users, CommitMessageAId: 140, CommitMessageBId: 138},
{Users: users, CommitMessageAId: 141, CommitMessageBId: 143},
{Users: users, CommitMessageAId: 148, CommitMessageBId: 146},
{Users: users, CommitMessageAId: 150, CommitMessageBId: 151},
{Users: users, CommitMessageAId: 154, CommitMessageBId: 153},
{Users: users, CommitMessageAId: 158, CommitMessageBId: 157},
{Users: users, CommitMessageAId: 161, CommitMessageBId: 163},
{Users: users, CommitMessageAId: 166, CommitMessageBId: 168},
{Users: users, CommitMessageAId: 169, CommitMessageBId: 172},
{Users: users, CommitMessageAId: 176, CommitMessageBId: 174},
{Users: users, CommitMessageAId: 179, CommitMessageBId: 177},
{Users: users, CommitMessageAId: 184, CommitMessageBId: 182},
{Users: users, CommitMessageAId: 185, CommitMessageBId: 187},
{Users: users, CommitMessageAId: 192, CommitMessageBId: 191},
{Users: users, CommitMessageAId: 196, CommitMessageBId: 195},
{Users: users, CommitMessageAId: 198, CommitMessageBId: 197},
{Users: users, CommitMessageAId: 203, CommitMessageBId: 204},
{Users: users, CommitMessageAId: 207, CommitMessageBId: 208},
{Users: users, CommitMessageAId: 210, CommitMessageBId: 211},
{Users: users, CommitMessageAId: 214, CommitMessageBId: 213},
{Users: users, CommitMessageAId: 220, CommitMessageBId: 219},
{Users: users, CommitMessageAId: 221, CommitMessageBId: 223},
{Users: users, CommitMessageAId: 228, CommitMessageBId: 226},
{Users: users, CommitMessageAId: 230, CommitMessageBId: 231},
{Users: users, CommitMessageAId: 233, CommitMessageBId: 236},
{Users: users, CommitMessageAId: 240, CommitMessageBId: 237},
{Users: users, CommitMessageAId: 241, CommitMessageBId: 244},
{Users: users, CommitMessageAId: 245, CommitMessageBId: 247},
{Users: users, CommitMessageAId: 251, CommitMessageBId: 250},
{Users: users, CommitMessageAId: 254, CommitMessageBId: 256},
{Users: users, CommitMessageAId: 257, CommitMessageBId: 260},
{Users: users, CommitMessageAId: 264, CommitMessageBId: 261},
{Users: users, CommitMessageAId: 268, CommitMessageBId: 265},
{Users: users, CommitMessageAId: 271, CommitMessageBId: 269},
{Users: users, CommitMessageAId: 273, CommitMessageBId: 274},
{Users: users, CommitMessageAId: 279, CommitMessageBId: 278},
{Users: users, CommitMessageAId: 284, CommitMessageBId: 281},
{Users: users, CommitMessageAId: 287, CommitMessageBId: 288},
{Users: users, CommitMessageAId: 291, CommitMessageBId: 292},
{Users: users, CommitMessageAId: 294, CommitMessageBId: 295},
{Users: users, CommitMessageAId: 300, CommitMessageBId: 297},
{Users: users, CommitMessageAId: 302, CommitMessageBId: 304},
{Users: users, CommitMessageAId: 307, CommitMessageBId: 305},
{Users: users, CommitMessageAId: 312, CommitMessageBId: 309},
{Users: users, CommitMessageAId: 314, CommitMessageBId: 316},
{Users: users, CommitMessageAId: 318, CommitMessageBId: 319},
{Users: users, CommitMessageAId: 324, CommitMessageBId: 323},
{Users: users, CommitMessageAId: 325, CommitMessageBId: 326},
{Users: users, CommitMessageAId: 332, CommitMessageBId: 329},
{Users: users, CommitMessageAId: 335, CommitMessageBId: 336},
{Users: users, CommitMessageAId: 338, CommitMessageBId: 340},
{Users: users, CommitMessageAId: 343, CommitMessageBId: 341},
{Users: users, CommitMessageAId: 347, CommitMessageBId: 348},
{Users: users, CommitMessageAId: 350, CommitMessageBId: 352},
{Users: users, CommitMessageAId: 356, CommitMessageBId: 353},
{Users: users, CommitMessageAId: 359, CommitMessageBId: 358},
{Users: users, CommitMessageAId: 361, CommitMessageBId: 362},
{Users: users, CommitMessageAId: 365, CommitMessageBId: 367},
{Users: users, CommitMessageAId: 370, CommitMessageBId: 369},
{Users: users, CommitMessageAId: 375, CommitMessageBId: 374},
{Users: users, CommitMessageAId: 377, CommitMessageBId: 379},
{Users: users, CommitMessageAId: 382, CommitMessageBId: 381},
{Users: users, CommitMessageAId: 386, CommitMessageBId: 388},
{Users: users, CommitMessageAId: 389, CommitMessageBId: 392},
{Users: users, CommitMessageAId: 395, CommitMessageBId: 396},
{Users: users, CommitMessageAId: 399, CommitMessageBId: 398},
{Users: users, CommitMessageAId: 401, CommitMessageBId: 402},
{Users: users, CommitMessageAId: 406, CommitMessageBId: 405},
{Users: users, CommitMessageAId: 411, CommitMessageBId: 412},
{Users: users, CommitMessageAId: 414, CommitMessageBId: 413},
{Users: users, CommitMessageAId: 417, CommitMessageBId: 419},
{Users: users, CommitMessageAId: 421, CommitMessageBId: 423},
{Users: users, CommitMessageAId: 425, CommitMessageBId: 426},
{Users: users, CommitMessageAId: 429, CommitMessageBId: 430},
{Users: users, CommitMessageAId: 435, CommitMessageBId: 433},
{Users: users, CommitMessageAId: 437, CommitMessageBId: 439},
{Users: users, CommitMessageAId: 443, CommitMessageBId: 442},
{Users: users, CommitMessageAId: 448, CommitMessageBId: 445},
{Users: users, CommitMessageAId: 449, CommitMessageBId: 450},
{Users: users, CommitMessageAId: 455, CommitMessageBId: 456},
{Users: users, CommitMessageAId: 458, CommitMessageBId: 460},
{Users: users, CommitMessageAId: 462, CommitMessageBId: 463},
{Users: users, CommitMessageAId: 466, CommitMessageBId: 468},
{Users: users, CommitMessageAId: 472, CommitMessageBId: 470},
{Users: users, CommitMessageAId: 475, CommitMessageBId: 474},
{Users: users, CommitMessageAId: 478, CommitMessageBId: 477},
}
	_ = database.Db.SaveDuels(&seeds)
}
