definitions:
  views.DiffRequest:
    properties:
      content:
        type: string
    type: object
  views.DiffResponse:
    properties:
      commit_messages:
        items:
          type: integer
        type: array
      content:
        type: string
      id:
        type: integer
    type: object
  views.DiffsResponse:
    properties:
      diffs:
        items:
          $ref: '#/definitions/views.DiffResponse'
        type: array
    type: object
info:
  contact: {}
  description: This is the commitinder server api.
  title: Commitinder Server
  version: "1.0"
paths:
  /diffs:
    get:
      consumes:
      - application/json
      description: A route to get all diffs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.DiffsResponse'
      summary: Get all diffs
      tags:
      - Diff
    post:
      consumes:
      - application/json
      description: A route to save a new diff
      parameters:
      - description: diffRequest
        in: body
        name: diffRequest
        required: true
        schema:
          $ref: '#/definitions/views.DiffRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/views.DiffResponse'
      summary: Save a new diff
      tags:
      - Diff
  /diffs/:id:
    get:
      consumes:
      - application/json
      description: A route to get a diff by id
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/views.DiffResponse'
      summary: Get a diff
      tags:
      - Diff
swagger: "2.0"
